import { expect, test } from '@playwright/test';

test('materials, trash, summary RAG and novel switching stay isolated', async ({page,request})=>{
  const project=await (await request.post('/api/v1/projects',{data:{title:'连续性验收小说'}})).json();
  const other=await (await request.post('/api/v1/projects',{data:{title:'完全隔离的另一本'}})).json();
  const base='/api/v1/projects/'+project.id;
  await request.post(base+'/nodes',{data:{kind:'chapter',title:'第一章 · 雾港',order_index:1}});
  await page.goto('/');
  await page.getByLabel('当前小说项目').selectOption(project.id);
  await page.getByRole('button',{name:'参考资料',exact:true}).click();
  await page.getByRole('button',{name:'新建素材',exact:true}).click();
  const editor=page.getByRole('dialog',{name:'新建素材'});
  await editor.getByLabel('素材标题').fill('林渡的铜钥匙');
  await editor.getByLabel('设定内容').fill('只有林渡持有这枚铜钥匙，钥匙不能打开钟楼。');
  await editor.getByRole('button',{name:'保存素材'}).click();
  await expect(editor).not.toBeVisible();
  await page.locator('.material-row').filter({hasText:'林渡的铜钥匙'}).click();
  await page.getByRole('button',{name:'固定素材',exact:true}).click();
  await expect(page.getByRole('button',{name:'取消固定',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'编辑素材',exact:true}).click();
  await page.getByLabel('设定内容').fill('只有林渡持有铜钥匙，钥匙能打开钟楼。');
  await page.getByRole('button',{name:'保存素材',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'编辑素材'})).not.toBeVisible();
  await page.getByRole('dialog',{name:'素材详情'}).getByRole('button',{name:'关闭对话框'}).click();
  await page.getByRole('button',{name:'参考资料',exact:true}).click();
  await expect(page.locator('.quick-reference').filter({hasText:'林渡的铜钥匙'})).toBeVisible();
  await page.getByLabel('搜索本项目素材').fill('铜钥匙');
  await expect(page.locator('.material-row').filter({hasText:'林渡的铜钥匙'})).toBeVisible();
  await page.getByRole('dialog',{name:'参考资料'}).getByRole('button',{name:'关闭对话框'}).click();
  await page.getByRole('button',{name:'查看正文'}).click();
  await page.getByLabel('章节正文').fill('林渡在雾港拾起铜钥匙，约定明夜前往钟楼。');
  await page.getByRole('button',{name:'完成本章',exact:true}).click();
  await expect(page.getByText('正文已保存，总结任务已提交。可离开页面，稍后查看结果。')).toBeVisible();
  await page.getByText('章节总结与连续性',{exact:true}).click();
  await expect(page.locator('.summary-panel').getByText('AI 总结',{exact:true})).toBeVisible();
  const results=await (await request.get(base+'/library/search?q='+encodeURIComponent('铜钥匙'))).json();
  expect(results.items.some((item:{type:string})=>item.type==='summary')).toBe(true);
  // Summary publication can finish before the submitting form's post-save refresh.
  await expect(page.getByRole('button',{name:'保存工作副本',exact:true})).toBeEnabled();
  await page.getByLabel('当前小说项目').selectOption(other.id);
  await expect(page.getByLabel('当前小说项目')).toHaveValue(other.id);
  await expect(page.getByRole('heading',{name:'聊聊这个故事',exact:true})).toBeVisible();
  await expect(page.getByLabel('给 AI 的消息')).toBeVisible();
  await expect(page.getByText('林渡的铜钥匙',{exact:true})).toHaveCount(0);
  await page.getByLabel('当前小说项目').selectOption(project.id);
  await expect(page.getByLabel('当前小说项目')).toHaveValue(project.id);
  await expect(page.getByRole('heading',{name:'第一章 · 雾港',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'查看正文'}).click();
  await expect(page.getByLabel('章节正文')).toHaveValue('林渡在雾港拾起铜钥匙，约定明夜前往钟楼。');
  await page.getByRole('button',{name:'参考资料',exact:true}).click();
  await page.locator('.material-row').filter({hasText:'林渡的铜钥匙'}).click();
  await page.getByRole('button',{name:'编辑素材',exact:true}).click();
  await page.getByRole('button',{name:'移到回收站',exact:true}).click();
  await page.getByRole('button',{name:'确认移到回收站',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'编辑素材'})).not.toBeVisible();
  await page.getByRole('dialog',{name:'素材详情'}).getByRole('button',{name:'关闭对话框'}).click();
  await page.getByRole('button',{name:'资料库',exact:true}).click();
  await page.getByRole('button',{name:'回收站',exact:true}).click();
  await expect(page.getByRole('button',{name:'永久删除林渡的铜钥匙'})).toBeDisabled();
  await page.getByRole('button',{name:'恢复林渡的铜钥匙'}).click();
  await expect(page.getByText('回收站为空。')).toBeVisible();
});

for(const width of [1440,1024,900,762,651,390]){
  test('chat workspace remains usable at '+width+'px',async({page,request})=>{
    await page.setViewportSize({width,height:960});
    const project=await (await request.post('/api/v1/projects',{data:{title:'雾城来信 · '+width}})).json();
    const base='/api/v1/projects/'+project.id;
    const chapter=await (await request.post(base+'/nodes',{data:{kind:'chapter',title:'第一章 · 雾潮来时',order_index:1}})).json();
    await request.post(base+'/library/entity',{data:{title:'林渡',content:'旧城邮差。遗失了七年前的记忆，随身携带一枚停走的怀表。'}});
    const original = await (await request.get(base+'/chapters/'+chapter.id)).json();
    expect((await request.put(base+'/chapters/'+chapter.id,{data:{content:'雾潮退到第七根系缆柱时，林渡才看清那封信。',contract:{}, revision: original.revision}})).status()).toBe(200);
    await page.goto('/');
    await page.getByLabel('当前小说项目').selectOption(project.id);
    await expect(page.getByLabel('给 AI 的消息')).toBeVisible();
    const workspaceBounds=await page.getByRole('main',{name:'创作工作区'}).boundingBox();
    expect(workspaceBounds?.width).toBeGreaterThan(width*0.5);
    await expect(page.getByLabel('章节正文')).toHaveCount(0);
    await expect(page.getByRole('navigation',{name:'创作空间'}).getByRole('button')).toHaveCount(3);
    await page.screenshot({path:'test-results/chat-'+width+'.png',fullPage:true});
    await page.getByRole('button',{name:'参考资料',exact:true}).click();
    await page.locator('.material-row').filter({hasText:'林渡'}).click();
    await expect(page.getByRole('dialog',{name:'素材详情'}).getByText('旧城邮差。',{exact:false})).toBeVisible();
    await page.getByRole('dialog').getByRole('button',{name:'关闭对话框'}).click();
    if(width>640){
      const before = await page.getByRole('complementary',{name:'小说导航'}).boundingBox();
      const separator=page.getByRole('separator',{name:'调整导航栏宽度'});
      await separator.focus();await page.keyboard.press('ArrowRight');
      await expect(separator).toHaveAttribute('aria-valuenow','224');
      const after = await page.getByRole('complementary',{name:'小说导航'}).boundingBox();
      expect(after!.width).toBeGreaterThan(before!.width);
    }
    await page.getByRole('button',{name:'查看正文'}).click();
    await expect(page.getByLabel('章节正文')).toHaveValue('雾潮退到第七根系缆柱时，林渡才看清那封信。');
    await page.getByRole('button',{name:'收起正文'}).click();
    expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false);
    await expect(page.getByRole('button',{name:'创建新小说'})).toBeVisible();
  });
}

test('chat persists across reload and settings safely configure an optional API',async({page,request})=>{
  const project=await (await request.post('/api/v1/projects',{data:{title:'对话设置验收'}})).json();
  await page.goto('/');await page.getByLabel('当前小说项目').selectOption(project.id);
  await page.getByLabel('给 AI 的消息').fill('讨论雾城邮差的开场');
  await page.getByRole('button',{name:'发送消息'}).click();
  await expect(page.locator('.assistant-prose')).toContainText('离线演示');
  await page.reload();
  await expect(page.locator('.author-message')).toContainText('讨论雾城邮差的开场');
  await request.post('/api/v1/projects/'+project.id+'/nodes',{data:{kind:'chapter',title:'新建第一章',order_index:1}});
  await page.reload();
  await page.getByRole('button',{name:'全书讨论',exact:true}).click();
  await expect(page.locator('.author-message')).toContainText('讨论雾城邮差的开场');
  await page.getByRole('button',{name:'设置',exact:true}).click();
  await page.getByLabel('运行模式').selectOption('api');
  await page.getByLabel('API 地址').fill('https://example.com/v1');
  await page.getByLabel('模型名称').fill('test-model');
  await page.getByLabel('API Key').fill('fake-e2e-key-not-real');
  await expect(page.getByRole('button',{name:'保存设置'})).toBeDisabled();
  await page.getByRole('checkbox', { name: '允许将当前任务的对话、正文及相关资料发送给此 API 服务商。可能产生费用。', exact: true }).check();
  await page.getByRole('button',{name:'保存设置'}).click();
  await expect(page.getByText('设置已保存，新请求将使用此配置。')).toBeVisible();
  await expect(page.getByLabel('API Key')).toHaveValue('');
  await page.reload();
  await page.getByRole('button',{name:'设置',exact:true}).click();
  await expect(page.getByLabel('API Key')).toHaveAttribute('placeholder','已安全保存，留空保持不变');
  await page.getByRole('button',{name:'移除密钥'}).click();
  await page.getByRole('button',{name:'保存设置'}).click();
  await expect(page.getByRole('button',{name:'移除密钥'})).toHaveCount(0);
  await page.getByRole('button',{name:'测试连接'}).click();
  await expect(page.getByText('连接成功，可以开始创作。')).toBeVisible();
});
